# Generated by Django 5.2.4 on 2025-07-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customdish_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plats',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('panier', 'Panier'), ('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('termine', 'Terminé')], default='panier', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customdish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order')),
            ],
        ),
    ]
