# Generated by Django 5.2.4 on 2025-08-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_plats_userprofile_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base_images/'),
        ),
    ]
