# Generated by Django 5.2.4 on 2025-08-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_ingredient_allergenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='base',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('legume', 'Légume'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('fromage', 'Fromage'), ('sauce', 'Sauce'), ('epice', 'Épice'), ('protéine', 'Protéine'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='base',
            unique_together={('nom', 'restaurant')},
        ),
    ]
