# Generated by Django 5.2.4 on 2025-08-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_base_restaurant_ingredient_restaurant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='plat_du_jour',
            field=models.BooleanField(default=False, help_text='Ce plat est-il le plat du jour ?'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('suspendu', 'Suspendu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='validé_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('plat_du_jour', True)), fields=('restaurant',), name='unique_plat_du_jour_par_restaurant'),
        ),
    ]
