# Generated by Django 5.2.4 on 2025-08-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menuitem_plat_du_jour_restaurant_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
