# Generated by Django 5.2.4 on 2025-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
