# Generated by Django 5.2.4 on 2025-08-18 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('panier', 'Panier'), ('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('termine', 'Terminé')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
