# Generated by Django 5.2.4 on 2025-08-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_orderstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='temps_preparation',
            field=models.PositiveIntegerField(blank=True, help_text='Temps en minutes', null=True),
        ),
    ]
