# Generated by Django 5.2.4 on 2025-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_paymentmethod_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('panier', 'Panier'), ('en_attente_paiement', 'En attente de paiement'), ('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('termine', 'Terminé')], default='panier', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='status',
            field=models.CharField(choices=[('panier', 'Panier'), ('en_attente_paiement', 'En attente de paiement'), ('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('termine', 'Terminé')], max_length=20),
        ),
    ]
