# Generated by Django 5.2.4 on 2025-08-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_order_status_alter_orderstatuslog_status'),
    ]

    operations = [
        # Supprimer les modèles de paiement
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        
        # Supprimer le champ wave_payment_link du restaurant
        migrations.RemoveField(
            model_name='restaurant',
            name='wave_payment_link',
        ),
        
        # Remettre le modèle Order comme il était
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('panier', 'Panier'),
                    ('en_attente', 'En attente'),
                    ('en_preparation', 'En préparation'),
                    ('pret', 'Prêt'),
                    ('termine', 'Terminé'),
                    ('annule', 'Annulé'),
                ],
                default='panier',
                max_length=20
            ),
        ),
        
        # Ajouter le champ total_amount avec une valeur par défaut
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                default=0.00
            ),
        ),
        
        # Ajouter le champ items
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list),
        ),
        
        # Ajouter le champ restaurant
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='api.restaurant',
                default=1
            ),
            preserve_default=False,
        ),
        
        # Supprimer les champs qui n'existent plus
        migrations.RemoveField(
            model_name='order',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='device_id',
        ),
        
        # Supprimer les modèles qui n'existent plus
        migrations.DeleteModel(
            name='OrderStatusLog',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        
        # Remettre le modèle UserProfile comme il était
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
        
        # Remettre le modèle CustomDish comme il était
        migrations.RemoveField(
            model_name='customdish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customdish',
            name='prix',
        ),
        migrations.AddField(
            model_name='customdish',
            name='prix_total',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='customdish',
            name='disponible',
            field=models.BooleanField(
                default=True,
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='customdish',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='customdish',
            name='restaurant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='custom_dishes',
                to='api.restaurant'
            ),
        ),
        
        # Créer le modèle CustomDishIngredient
        migrations.CreateModel(
            name='CustomDishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('custom_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customdish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
            ],
            options={
                'unique_together': {('custom_dish', 'ingredient')},
            },
        ),
        
        # Remettre le modèle Restaurant comme il était
        migrations.AlterField(
            model_name='restaurant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='statut',
            field=models.CharField(
                choices=[
                    ('actif', 'Actif'),
                    ('inactif', 'Inactif'),
                    ('suspendu', 'Suspendu'),
                    ('en_attente', 'En attente de validation'),
                ],
                default='actif',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
